openapi: "3.0.3"
info:
  title: Graph Query API
  version: "0.5.0"
  description: |
    Micro-API for querying network topology (mock mode) and telemetry.
    Used by Foundry agents via OpenApiTool.
    Backend: Mock (static responses, no external dependency)
# NOTE: Template placeholders ({base_url}, etc.) are substituted
# at runtime by scripts/provision_agents.py.
servers:
  - url: "{base_url}"
    description: Deployed Container App

paths:
  /query/graph:
    post:
      operationId: query_graph
      summary: Query the network topology graph (mock mode)
      description: |
        Sends a query to the mock graph backend, which returns static
        network topology data for offline demonstrations and testing.
        Send any query string — natural language or formal syntax.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: |
                    A query string (natural language or formal syntax).
                    The mock backend returns representative sample data.
                    Example: "find all core routers"
      responses:
        "200":
          description: Query results (check 'error' field for query failures)
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                  data:
                    type: array
                    items:
                      type: object
                  error:
                    type: string
                    nullable: true
                    description: |
                      If present, the query failed. Contains the error message.
                      Read the message, fix your query, and retry.

  /query/telemetry:
    post:
      operationId: query_telemetry
      summary: Execute a KQL query against telemetry data in Fabric Eventhouse
      description: |
        Submits a KQL query to a telemetry table in Fabric Eventhouse.
        Returns columns and rows of alert or telemetry data.
        Tables available: AlertStream (~5000 rows), LinkTelemetry (~8640 rows).
        Use standard KQL syntax: table | where | project | order by | take.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: |
                    A KQL query string.
                    Example: AlertStream | where Severity == 'CRITICAL' | order by Timestamp desc | take 5
      responses:
        "200":
          description: Query results (check 'error' field for query failures)
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                  rows:
                    type: array
                    items:
                      type: object
                  error:
                    type: string
                    nullable: true
                    description: |
                      If present, the query failed. Contains the error message.
                      Read the message, fix your query, and retry.
