openapi: "3.0.3"
info:
  title: Graph Query API
  version: "0.5.0"
  description: |
    Micro-API for executing GQL and telemetry queries against Microsoft Fabric.
    Used by Foundry agents via OpenApiTool.
    Backend: Fabric GraphModel (GQL)
# NOTE: Template placeholders ({base_url}, {workspace_id}, etc.) are substituted
# at runtime by scripts/provision_agents.py. This raw file is NOT a valid OpenAPI
# spec until those values are replaced. See provision_agents.py::_load_openapi_spec().
servers:
  - url: "{base_url}"
    description: Deployed Container App

paths:
  /query/graph:
    post:
      operationId: query_graph
      summary: Execute a GQL query against the Fabric ontology graph
      description: |
        Submits a GQL (Graph Query Language) query to the Fabric GraphModel.
        Returns columns and data rows from the network topology ontology.
        Use this to query routers, links, switches, base stations, MPLS paths,
        services, SLA policies, and BGP sessions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - workspace_id
                - graph_model_id
              properties:
                query:
                  type: string
                  description: |
                    A GQL query string. Use exact entity IDs (uppercase with hyphens).
                    Never wrap values in LOWER(). Example:
                    MATCH (mp:MPLSPath)-[:routes_via]->(tl:TransportLink)
                    WHERE tl.LinkId = "LINK-SYD-MEL-FIBRE-01"
                    RETURN mp.PathId, mp.PathType
                workspace_id:
                  type: string
                  enum: ["{workspace_id}"]
                  description: Fabric workspace GUID. Always use the value shown.
                graph_model_id:
                  type: string
                  enum: ["{graph_model_id}"]
                  description: GraphModel item GUID. Always use the value shown.
      responses:
        "200":
          description: Query results (check 'error' field for query failures)
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                  data:
                    type: array
                    items:
                      type: object
                  error:
                    type: string
                    nullable: true
                    description: |
                      If present, the query failed. Contains the error message.
                      Read the message, fix your query, and retry.

  /query/telemetry:
    post:
      operationId: query_telemetry
      summary: Execute a SQL query against telemetry data in Cosmos DB
      description: |
        Submits a Cosmos SQL query to a telemetry container in Azure Cosmos DB NoSQL.
        Returns columns and rows of alert or telemetry data.
        Containers available: AlertStream (~5000 docs), LinkTelemetry (~8640 docs).
        Use standard SQL syntax: SELECT, FROM c, WHERE, ORDER BY, TOP, GROUP BY.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - container_name
              properties:
                query:
                  type: string
                  description: |
                    A Cosmos SQL query string.
                    Always use FROM c as the alias.
                    Example: SELECT c.AlertId, c.Severity, c.Description FROM c WHERE c.Severity = 'CRITICAL' ORDER BY c.Timestamp DESC OFFSET 0 LIMIT 5
                container_name:
                  type: string
                  enum: ["AlertStream", "LinkTelemetry"]
                  description: |
                    The Cosmos DB container to query.
                    Use "AlertStream" for network alerts.
                    Use "LinkTelemetry" for link telemetry readings.
      responses:
        "200":
          description: Query results (check 'error' field for query failures)
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                  rows:
                    type: array
                    items:
                      type: object
                  error:
                    type: string
                    nullable: true
                    description: |
                      If present, the query failed. Contains the error message.
                      Read the message, fix your query, and retry.
